const products = [
  {
    id: 1,
    title: "Esponja 3D Dazzle",
    categoty: "makeup",
    quantity: null,
    price: 36.9,
    discount_price: 29.9,
    img: "./assets/mais-vendidos-esponja-3d-dazzle.svg",
    section: "best sellers",
  },
  {
    id: 2,
    title: "Base Líquida Hyaluronic Hydra Dazzle Escuro 2",
    categoty: "makeup",
    quantity: "500g",
    price: 89.9,
    discount_price: null,
    img: "./assets/mais-vendidos-base-liquida-dazzle-escuro-2.svg",
    section: "best sellers",
  },
  {
    id: 3,
    title: "Grace La Rose Sublime Deo Colônia Pocket",
    categoty: "fragrance",
    quantity: "15ml",
    price: 39.9,
    discount_price: null,
    img: "./assets/mais-vendidos-grace-la-rose-colonia.svg",
    section: "best sellers",
  },
  {
    id: 4,
    title: "Pó Compacto HD Cover Claro 2 Dazzle",
    categoty: "makeup",
    quantity: "12g",
    price: 46.9,
    discount_price: null,
    img: "./assets/mais-vendidos-po-compacto-dazzle.svg",
    section: "best sellers",
  },
  {
    id: 5,
    title: "Venyx L'Or",
    categoty: "fragrance",
    quantity: "100ml",
    price: 150.0,
    discount_price: null,
    img: "./assets/featured-venyx-perfume.svg",
    section: "featured",
  },
  {
    id: 6,
    title: "Multi-Vit Complex A-Z Mulheres",
    categoty: "energy and performance",
    quantity: "60 Cápsulas",
    price: 85.0,
    discount_price: null,
    img: "./assets/featured-multi-vitamina-a-z.svg",
    section: "featured",
  },
  {
    id: 7,
    title: "Corps Lígnea Body Contour Gel Modelador",
    categoty: "body and bath",
    quantity: "500g",
    price: 60.0,
    discount_price: null,
    img: "./assets/os-mais-desejados-corps-lignea-gel-modelador.svg",
    section: "most wanted",
  },
  {
    id: 8,
    title: "Shake de Vanilla H+ HND",
    categoty: "energy and performance",
    quantity: "550g",
    price: 99.9,
    discount_price: 79.9,
    img: "./assets/os-mais-desejados-shake-de-vanilla.svg",
    section: "most wanted",
  },
  {
    id: 9,
    title: "Shake de Morango H+ HND",
    categoty: "energy and performance",
    quantity: "550g",
    price: 99.9,
    discount_price: 79.9,
    img: "./assets/os-mais-desejados-shake-de-morango.svg",
    section: "most wanted",
  },
  {
    id: 10,
    title: "Luva de Silicone Creme para as Mãos Hands",
    categoty: "body and bath",
    quantity: "100g",
    price: 25.0,
    discount_price: null,
    img: "./assets/os-mais-desejados-luva-de-silicone-creme.svg",
    section: " most wanted",
  },
  {
    id: 11,
    title: "Café Verde",
    categoty: "energy and performance",
    quantity: "120 Cápsulas",
    price: 69.9,
    discount_price: null,
    img: "./assets/vida-saudavel-cafe-verde.svg",
    section: "healthy life",
  },
  {
    id: 12,
    title: "Ácido Hialurônico com Colágeno HND",
    categoty: "body and bath",
    quantity: "30 Sachês de 4g",
    price: 175.0,
    discount_price: null,
    img: "./assets/vida-saudavel-acido-hialuronico.svg",
    section: "healthy life",
  },
  {
    id: 13,
    title: "Slim Max HND",
    categoty: "energy and performance",
    quantity: "120 Cápsulas",
    price: 140.0,
    discount_price: null,
    img: "./assets/vida-saudavel-slim-max.svg",
    section: "healthy life",
  },
  {
    id: 14,
    title: "Chá H+ Frutas Vermelhas",
    categoty: "energy and performance",
    quantity: "150g",
    price: 85.0,
    discount_price: null,
    img: "./assets/vida-saudavel-cha-h-frutas-vermelhas.svg",
    section: "healthy life",
  },
  {
    id: 15,
    title: "Corps Lígnea Wonderful Gold Óleo para as Pernas",
    categoty: "body and bath",
    quantity: "150ml",
    price: 45.0,
    discount_price: null,
    img: "./assets/corpo-banho-oleo-para-pernas-wondefurl.svg",
    section: "body and bath",
  },
  {
    id: 16,
    title: "Corps Lígnea Body Contour Esfoliante Corporal",
    categoty: "body and bath",
    quantity: "200g",
    price: 49.0,
    discount_price: null,
    img: "./assets/corpo-banho-corps-linea-esfoliante-corporal.svg",
    section: "body and bath",
  },
  {
    id: 17,
    title: "Gel para Massagem Feelin Hot Morango",
    categoty: "body and bath",
    quantity: "60ml",
    price: 27.0,
    discount_price: null,
    img: "./assets/corpo-banho-gel-para-massagem-morango.svg",
    section: "body and bath",
  },
  {
    id: 18,
    title: "Óleo para Pernas Wonderful",
    categoty: "body and bath",
    quantity: "140ml",
    price: 39.9,
    discount_price: null,
    img: "./assets/corpo-banho-oleo-para-pernas-wondefurl.svg",
    section: "body and bath",
  },
  {
    id: 19,
    title: "Gel para Massagem Feelin Hot Cereja com Champanhe",
    categoty: "body and bath",
    quantity: "60ml",
    price: 27.0,
    discount_price: null,
    img: "./assets/corpo-banho-corps-linea-gel-para-massagem-cereja.svg",
    section: "body and bath",
  },
  {
    id: 20,
    title: "Desodorante Corporal jOLi Cupuaçu",
    categoty: "body and bath",
    quantity: "140g",
    price: 60.0,
    discount_price: null,
    img: "./assets/corpo-banho-joli-desodorante-corporal.svg",
    section: "body and bath",
  },
  {
    id: 21,
    title: "Corps Lígnea Body Contour Gel Modelador",
    categoty: "body and bath",
    quantity: "500g",
    price: 60.0,
    discount_price: null,
    img: "./assets/corpo-banho-gel.svg",
    section: "body and bath",
  },
  {
    id: 22,
    title: "Loção Hidratante Strax",
    categoty: "body and bath",
    quantity: "240ml",
    price: 60.0,
    discount_price: null,
    img: "./assets/corpo-banho-hidratante.svg",
    section: "body and bath",
  },
  {
    id: 23,
    title: "Lattitude Expedition",
    categoty: "fragrance",
    quantity: "100ml",
    price: 129.0,
    discount_price: null,
    img: "./assets/fragancias-lattitude.svg",
    section: "fragrance",
  },
  {
    id: 24,
    title: "Empire VIP",
    categoty: "fragrance",
    quantity: "100ml",
    price: 150.0,
    discount_price: null,
    img: "./assets/fragancias-empire-vip.svg",
    section: "fragrance",
  },
  {
    id: 25,
    title: "Empire",
    categoty: "fragrance",
    quantity: "100ml",
    price: 150.0,
    discount_price: null,
    img: "./assets/fragancias-empire.svg",
    section: "fragrance",
  },
  {
    id: 26,
    title: "Lattitude Stamina",
    categoty: "fragrance",
    quantity: "100ml",
    price: 129.0,
    discount_price: null,
    img: "./assets/fragancias-lattitude-stamina.svg",
    section: "fragrance",
  },
  {
    id: 27,
    title: "Empire Gold",
    categoty: "fragrance",
    quantity: "100ml",
    price: 150.0,
    discount_price: null,
    img: "./assets/fragancias-empire-gold.svg",
    section: "fragrance",
  },
  {
    id: 28,
    title: "Colônia Lattitude Origini",
    categoty: "fragrance",
    quantity: "100ml",
    price: 129.0,
    discount_price: null,
    img: "./assets/fragancias-lattitude-origini.svg",
    section: "fragrance",
  },
  {
    id: 29,
    title: "Colônia Ella Juicy",
    categoty: "fragrance",
    quantity: "100ml",
    price: 129.0,
    discount_price: null,
    img: "./assets/fragancias-ella-juicy.svg",
    section: "fragrance",
  },
  {
    id: 30,
    title: "Spot For Her",
    categoty: "fragrance",
    quantity: "75ml",
    price: 129.0,
    discount_price: null,
    img: "./assets/fragancias-spot-for-her.svg",
    section: "fragrance",
  },
  {
    id: 31,
    title: "Deo Colônia Venyx L'Or",
    categoty: "fragrance",
    quantity: "100ml",
    price: 150.0,
    discount_price: null,
    img: "./assets/acabaram-de-chegar-deo-colonia-venyx.svg",
    section: "just arrived",
  },
  {
    id: 32,
    title: "Desodorante Roll On Dynamic",
    categoty: "bath and body",
    quantity: "70ml",
    price: 17.9,
    discount_price: null,
    img: "./assets/acabaram-de-chegar-desodorante.svg",
    section: "just arrived",
  },
  {
    id: 33,
    title: "Erva Doce Sabonete Cremoso Facial Hinode",
    categoty: "bath and body",
    quantity: "250ml",
    price: 33.4,
    discount_price: null,
    img: "./assets/acabaram-de-chegar-sabonete-cremoso-facial.svg",
    section: "just arrived",
  },
  {
    id: 34,
    title: "HND Shake Triple Chocolate",
    categoty: "energy and performance",
    quantity: "450g",
    price: 109.9,
    discount_price: null,
    img: "./assets/acabaram-de-chegar-hnd-shake-chocolate.svg",
    section: "just arrived",
  },
];
